

spring.application.name=demo
logging.level.org.springframework.web.client.RestClient=DEBUG


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.driver-class-name=org.postgresql.Driver

# Keeps your AR project tables in sync with your Java code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.key=${CHATBOT_API_KEY}


jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000


#spring.config.import=optional:classpath:api_key.env[.properties]

#spring.config.import=optional:file:api_key.env[.properties]  # run localy and not to Renderer 