

spring.application.name=demo
logging.level.org.springframework.web.client.RestClient=DEBUG


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.key=${CHATBOT_API_KEY}


jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000


brevo.api.key=${PASSWORD_EMAIL_CODE}


#spring.mail.host=smtp-relay.brevo.com
#spring.mail.port=465
#spring.mail.username=ab9625001@smtp-brevo.com
#spring.mail.password=${PASSWORD_EMAIL_CODE}

#spring.mail.properties.mail.smtp.auth=true
# Direct SSL does not use STARTTLS upgrades
#spring.mail.properties.mail.smtp.starttls.enable=false

# Force Java Mail to use the SSL Socket Factory over port 465
#spring.mail.properties.mail.smtp.socketFactory.port=465
#spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
#spring.mail.properties.mail.smtp.socketFactory.fallback=false

# Keep your safety timeouts active
#spring.mail.properties.mail.smtp.connectiontimeout=10000
#spring.mail.properties.mail.smtp.timeout=10000
#spring.mail.properties.mail.smtp.writetimeout=10000
# here 